[{"url":"https://api.github.com/repos/ICLRandD/Blackstone/issues/comments/549669496","html_url":"https://github.com/ICLRandD/Blackstone/issues/11#issuecomment-549669496","issue_url":"https://api.github.com/repos/ICLRandD/Blackstone/issues/11","id":549669496,"node_id":"MDEyOklzc3VlQ29tbWVudDU0OTY2OTQ5Ng==","user":{"login":"richyvk","id":4687812,"node_id":"MDQ6VXNlcjQ2ODc4MTI=","avatar_url":"https://avatars.githubusercontent.com/u/4687812?v=4","gravatar_id":"","url":"https://api.github.com/users/richyvk","html_url":"https://github.com/richyvk","followers_url":"https://api.github.com/users/richyvk/followers","following_url":"https://api.github.com/users/richyvk/following{/other_user}","gists_url":"https://api.github.com/users/richyvk/gists{/gist_id}","starred_url":"https://api.github.com/users/richyvk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/richyvk/subscriptions","organizations_url":"https://api.github.com/users/richyvk/orgs","repos_url":"https://api.github.com/users/richyvk/repos","events_url":"https://api.github.com/users/richyvk/events{/privacy}","received_events_url":"https://api.github.com/users/richyvk/received_events","type":"User","site_admin":false},"created_at":"2019-11-05T05:33:36Z","updated_at":"2019-11-05T05:33:36Z","author_association":"NONE","body":"Hi again. Trying to get Blackstone installed on my Macbook. I have Python 3.7.5 running in a venv. Have installed both Blackstone and the model (en-blackstone-proto 0.0.1) as per your README. \r\nWhen I try and run your \"Applying the NER model\" example I get an error:\r\n\r\n```Traceback (most recent call last):\r\n  File \"blackstone_test.py\", line 10, in <module>\r\n    doc = nlp(text)\r\n  File \"/Users/admin/Documents/Blackstone/blackstone/lib/python3.7/site-packages/spacy/language.py\", line 435, in __call__\r\n    doc = proc(doc, **component_cfg.get(name, {}))\r\n  File \"pipes.pyx\", line 396, in spacy.pipeline.pipes.Tagger.__call__\r\n  File \"pipes.pyx\", line 441, in spacy.pipeline.pipes.Tagger.set_annotations\r\n  File \"morphology.pyx\", line 312, in spacy.morphology.Morphology.assign_tag_id\r\n  File \"morphology.pyx\", line 200, in spacy.morphology.Morphology.add\r\nValueError: [E167] Unknown morphological feature: 'ConjType' (9141427322507498425). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:\r\npython -m spacy validate\r\n(blackstone) Admins-MacBook-Pro:Blackstone admin$ python -m spacy validate\r\n✔ Loaded compatibility table\r\n\r\n====================== Installed models (spaCy v2.2.2) ======================\r\nℹ spaCy installation:\r\n/Users/admin/Documents/Blackstone/blackstone/lib/python3.7/site-packages/spacy\r\n\r\nNo models found in your current environment.\r\n```\r\nNot sure if this a red herring but I noticed running `python -m spacy validate`, as the error suggested, mentions that No models found. But when I run pip list I can clearly see the model is installed.\r\n\r\nAny ideas how to get this sorted?\r\n\r\nIt fails on the line doc = nlp(text) so it seems like the model imports OK??","reactions":{"url":"https://api.github.com/repos/ICLRandD/Blackstone/issues/comments/549669496/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null,"event":"commented","actor":{"login":"richyvk","id":4687812,"node_id":"MDQ6VXNlcjQ2ODc4MTI=","avatar_url":"https://avatars.githubusercontent.com/u/4687812?v=4","gravatar_id":"","url":"https://api.github.com/users/richyvk","html_url":"https://github.com/richyvk","followers_url":"https://api.github.com/users/richyvk/followers","following_url":"https://api.github.com/users/richyvk/following{/other_user}","gists_url":"https://api.github.com/users/richyvk/gists{/gist_id}","starred_url":"https://api.github.com/users/richyvk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/richyvk/subscriptions","organizations_url":"https://api.github.com/users/richyvk/orgs","repos_url":"https://api.github.com/users/richyvk/repos","events_url":"https://api.github.com/users/richyvk/events{/privacy}","received_events_url":"https://api.github.com/users/richyvk/received_events","type":"User","site_admin":false}},{"url":"https://api.github.com/repos/ICLRandD/Blackstone/issues/comments/549677140","html_url":"https://github.com/ICLRandD/Blackstone/issues/11#issuecomment-549677140","issue_url":"https://api.github.com/repos/ICLRandD/Blackstone/issues/11","id":549677140,"node_id":"MDEyOklzc3VlQ29tbWVudDU0OTY3NzE0MA==","user":{"login":"richyvk","id":4687812,"node_id":"MDQ6VXNlcjQ2ODc4MTI=","avatar_url":"https://avatars.githubusercontent.com/u/4687812?v=4","gravatar_id":"","url":"https://api.github.com/users/richyvk","html_url":"https://github.com/richyvk","followers_url":"https://api.github.com/users/richyvk/followers","following_url":"https://api.github.com/users/richyvk/following{/other_user}","gists_url":"https://api.github.com/users/richyvk/gists{/gist_id}","starred_url":"https://api.github.com/users/richyvk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/richyvk/subscriptions","organizations_url":"https://api.github.com/users/richyvk/orgs","repos_url":"https://api.github.com/users/richyvk/repos","events_url":"https://api.github.com/users/richyvk/events{/privacy}","received_events_url":"https://api.github.com/users/richyvk/received_events","type":"User","site_admin":false},"created_at":"2019-11-05T06:10:02Z","updated_at":"2019-11-05T06:10:02Z","author_association":"NONE","body":"Hi again. Figured it out. Doesn't like spacy 2.2.*, rolled back to 2.1.8 and all good :)","reactions":{"url":"https://api.github.com/repos/ICLRandD/Blackstone/issues/comments/549677140/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null,"event":"commented","actor":{"login":"richyvk","id":4687812,"node_id":"MDQ6VXNlcjQ2ODc4MTI=","avatar_url":"https://avatars.githubusercontent.com/u/4687812?v=4","gravatar_id":"","url":"https://api.github.com/users/richyvk","html_url":"https://github.com/richyvk","followers_url":"https://api.github.com/users/richyvk/followers","following_url":"https://api.github.com/users/richyvk/following{/other_user}","gists_url":"https://api.github.com/users/richyvk/gists{/gist_id}","starred_url":"https://api.github.com/users/richyvk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/richyvk/subscriptions","organizations_url":"https://api.github.com/users/richyvk/orgs","repos_url":"https://api.github.com/users/richyvk/repos","events_url":"https://api.github.com/users/richyvk/events{/privacy}","received_events_url":"https://api.github.com/users/richyvk/received_events","type":"User","site_admin":false}}]