{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/868","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/868/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/868/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/868/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/868","id":682619849,"node_id":"MDU6SXNzdWU2ODI2MTk4NDk=","number":868,"title":"hello, have this bug when use merger","user":{"login":"tembel123456","id":38708587,"node_id":"MDQ6VXNlcjM4NzA4NTg3","avatar_url":"https://avatars.githubusercontent.com/u/38708587?v=4","gravatar_id":"","url":"https://api.github.com/users/tembel123456","html_url":"https://github.com/tembel123456","followers_url":"https://api.github.com/users/tembel123456/followers","following_url":"https://api.github.com/users/tembel123456/following{/other_user}","gists_url":"https://api.github.com/users/tembel123456/gists{/gist_id}","starred_url":"https://api.github.com/users/tembel123456/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tembel123456/subscriptions","organizations_url":"https://api.github.com/users/tembel123456/orgs","repos_url":"https://api.github.com/users/tembel123456/repos","events_url":"https://api.github.com/users/tembel123456/events{/privacy}","received_events_url":"https://api.github.com/users/tembel123456/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2020-08-20T10:55:00Z","updated_at":"2020-12-14T10:14:02Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"when i try change mask_mode  to some of Xseg, most time to xseg-prd*xseg-dst  , console show mi this\r\n\r\nDeepFaceLab_Linux/DeepFaceLab/merger/MergeMasked.py:238: RuntimeWarning: invalid value encountered in multiply\r\n  out_img = img_bgr*(1-img_face_mask_a) + (out_img*img_face_mask_a)\r\n\r\nthis show mi always, if i working with 1 proces, or 4\r\n\r\ncan somebody help my? Thanx and best regards\r\n\r\nPython 3.8.3 (default, Jul  2 2020, 16:21:59) \r\n[GCC 7.3.0] :: Anaconda, Inc. on linux","closed_by":null,"reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/868/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/868/timeline","performed_via_github_app":null,"state_reason":null}