{"url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/1070","repository_url":"https://api.github.com/repos/ludwig-ai/ludwig","labels_url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/1070/labels{/name}","comments_url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/1070/comments","events_url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/1070/events","html_url":"https://github.com/ludwig-ai/ludwig/issues/1070","id":775405859,"node_id":"MDU6SXNzdWU3NzU0MDU4NTk=","number":1070,"title":"TypeError: Failed to convert object of type <class 'list'> to Tensor.","user":{"login":"Bhavesh-Joshi","id":29869080,"node_id":"MDQ6VXNlcjI5ODY5MDgw","avatar_url":"https://avatars.githubusercontent.com/u/29869080?v=4","gravatar_id":"","url":"https://api.github.com/users/Bhavesh-Joshi","html_url":"https://github.com/Bhavesh-Joshi","followers_url":"https://api.github.com/users/Bhavesh-Joshi/followers","following_url":"https://api.github.com/users/Bhavesh-Joshi/following{/other_user}","gists_url":"https://api.github.com/users/Bhavesh-Joshi/gists{/gist_id}","starred_url":"https://api.github.com/users/Bhavesh-Joshi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Bhavesh-Joshi/subscriptions","organizations_url":"https://api.github.com/users/Bhavesh-Joshi/orgs","repos_url":"https://api.github.com/users/Bhavesh-Joshi/repos","events_url":"https://api.github.com/users/Bhavesh-Joshi/events{/privacy}","received_events_url":"https://api.github.com/users/Bhavesh-Joshi/received_events","type":"User","site_admin":false},"labels":[{"id":1174068769,"node_id":"MDU6TGFiZWwxMTc0MDY4NzY5","url":"https://api.github.com/repos/ludwig-ai/ludwig/labels/bug","name":"bug","color":"d73a4a","default":true,"description":"Something isn't working"},{"id":1434966350,"node_id":"MDU6TGFiZWwxNDM0OTY2MzUw","url":"https://api.github.com/repos/ludwig-ai/ludwig/labels/looking%20into%20it","name":"looking into it","color":"ffa54f","default":false,"description":""}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2020-12-28T13:40:05Z","updated_at":"2021-01-13T13:07:28Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\nAn error occurred while saving model with method **save_savedmodel**\r\n\r\n**TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, -1]. Consider casting elements to a supported type.**\r\n\r\n**To Reproduce**\r\nSteps to reproduce the behavior:\r\n1. Go to 'https://gist.github.com/Bhavesh-Joshi/4db376e4aa6a2ef808c4e54618acc987#file-vqa_train-py'\r\n2. Run vqa_train.py\r\n3. See an error\r\n\r\n**Expected behavior**\r\nThe model should be saved.\r\n\r\n**Environment :**\r\n - OS: Ubuntu\r\n - Version 20.04.1 LTS\r\n- Python version 3.6\r\n- Ludwig version 0.3\r\n\r\n**Additional context**\r\nJust want to add one scenario which I observed is the error only occurred when I train the model with the image dataset. With another kind of data like text, numbers it works fine.","closed_by":null,"reactions":{"url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/1070/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/1070/timeline","performed_via_github_app":null,"state_reason":null}