{"url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/110","repository_url":"https://api.github.com/repos/ludwig-ai/ludwig","labels_url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/110/labels{/name}","comments_url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/110/comments","events_url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/110/events","html_url":"https://github.com/ludwig-ai/ludwig/issues/110","id":411236502,"node_id":"MDU6SXNzdWU0MTEyMzY1MDI=","number":110,"title":"Question regarding: model.train(dataframe)","user":{"login":"pangka","id":44944904,"node_id":"MDQ6VXNlcjQ0OTQ0OTA0","avatar_url":"https://avatars.githubusercontent.com/u/44944904?v=4","gravatar_id":"","url":"https://api.github.com/users/pangka","html_url":"https://github.com/pangka","followers_url":"https://api.github.com/users/pangka/followers","following_url":"https://api.github.com/users/pangka/following{/other_user}","gists_url":"https://api.github.com/users/pangka/gists{/gist_id}","starred_url":"https://api.github.com/users/pangka/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pangka/subscriptions","organizations_url":"https://api.github.com/users/pangka/orgs","repos_url":"https://api.github.com/users/pangka/repos","events_url":"https://api.github.com/users/pangka/events{/privacy}","received_events_url":"https://api.github.com/users/pangka/received_events","type":"User","site_admin":false},"labels":[{"id":1174068775,"node_id":"MDU6TGFiZWwxMTc0MDY4Nzc1","url":"https://api.github.com/repos/ludwig-ai/ludwig/labels/waiting%20for%20answer","name":"waiting for answer","color":"fff36b","default":false,"description":"Further information is requested"}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":8,"created_at":"2019-02-17T21:20:39Z","updated_at":"2019-02-19T02:47:42Z","closed_at":"2019-02-19T02:47:42Z","author_association":"NONE","active_lock_reason":null,"body":"I'm using pandas to import a csv file :\r\ntraining_data = pd.read_csv(csv_file_path)\r\n\r\nYet when I use the ludwig api:\r\ntrain_stats = model.train(data_df=training_data)\r\n\r\nI get this error:\r\nFileNotFoundError: [WinError 2] The system cannot find the file specified\r\n\r\nI'm misunderstanding the api examples. My understanding is one can specify either a csv file path or a dataframe, yet am unable to get either to work properly.\r\n","closed_by":{"login":"pangka","id":44944904,"node_id":"MDQ6VXNlcjQ0OTQ0OTA0","avatar_url":"https://avatars.githubusercontent.com/u/44944904?v=4","gravatar_id":"","url":"https://api.github.com/users/pangka","html_url":"https://github.com/pangka","followers_url":"https://api.github.com/users/pangka/followers","following_url":"https://api.github.com/users/pangka/following{/other_user}","gists_url":"https://api.github.com/users/pangka/gists{/gist_id}","starred_url":"https://api.github.com/users/pangka/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pangka/subscriptions","organizations_url":"https://api.github.com/users/pangka/orgs","repos_url":"https://api.github.com/users/pangka/repos","events_url":"https://api.github.com/users/pangka/events{/privacy}","received_events_url":"https://api.github.com/users/pangka/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/110/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/ludwig-ai/ludwig/issues/110/timeline","performed_via_github_app":null,"state_reason":"completed"}