{"url":"https://api.github.com/repos/GantMan/nsfw_model/issues/77","repository_url":"https://api.github.com/repos/GantMan/nsfw_model","labels_url":"https://api.github.com/repos/GantMan/nsfw_model/issues/77/labels{/name}","comments_url":"https://api.github.com/repos/GantMan/nsfw_model/issues/77/comments","events_url":"https://api.github.com/repos/GantMan/nsfw_model/issues/77/events","html_url":"https://github.com/GantMan/nsfw_model/issues/77","id":718553745,"node_id":"MDU6SXNzdWU3MTg1NTM3NDU=","number":77,"title":"Finetune error: layer keras_layer expects 262 weights, but the saved weights have 260 elements","user":{"login":"chinalu","id":167307,"node_id":"MDQ6VXNlcjE2NzMwNw==","avatar_url":"https://avatars.githubusercontent.com/u/167307?v=4","gravatar_id":"","url":"https://api.github.com/users/chinalu","html_url":"https://github.com/chinalu","followers_url":"https://api.github.com/users/chinalu/followers","following_url":"https://api.github.com/users/chinalu/following{/other_user}","gists_url":"https://api.github.com/users/chinalu/gists{/gist_id}","starred_url":"https://api.github.com/users/chinalu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chinalu/subscriptions","organizations_url":"https://api.github.com/users/chinalu/orgs","repos_url":"https://api.github.com/users/chinalu/repos","events_url":"https://api.github.com/users/chinalu/events{/privacy}","received_events_url":"https://api.github.com/users/chinalu/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2020-10-10T07:13:10Z","updated_at":"2021-01-09T01:42:07Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"I want to feed more samples base on trained model,  to do some fine tune. But I got Error:\r\n\r\n`Traceback (most recent call last):\r\n  File \"make_nsfw_model.py\", line 273, in <module>\r\n    run_main()\r\n  File \"make_nsfw_model.py\", line 269, in run_main\r\n    app.run(main)\r\n  File \"/Users/bill/lab/py/nsfw_model/venv/lib/python3.7/site-packages/absl/app.py\", line 300, in run\r\n    _run_main(main, args)\r\n  File \"/Users/bill/lab/py/nsfw_model/venv/lib/python3.7/site-packages/absl/app.py\", line 251, in _run_main\r\n    sys.exit(main(argv))\r\n  File \"make_nsfw_model.py\", line 197, in main\r\n    FLAGS.tfhub_module, image_dir, hparams, FLAGS.image_size, FLAGS.saved_model_dir)\r\n  File \"/Users/bill/lab/py/nsfw_model/training/make_nsfw_model_lib.py\", line 427, in make_image_classifier\r\n    model.load_weights(existingWeightsPath)\r\n  File \"/Users/bill/lab/py/nsfw_model/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py\", line 234, in load_weights\r\n    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)\r\n  File \"/Users/bill/lab/py/nsfw_model/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py\", line 1222, in load_weights\r\n    hdf5_format.load_weights_from_hdf5_group(f, self.layers)\r\n  File \"/Users/bill/lab/py/nsfw_model/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py\", line 701, in load_weights_from_hdf5_group\r\n    str(len(weight_values)) + ' elements.')\r\nValueError: Layer #0 (named \"keras_layer\" in the current model) was found to correspond to layer keras_layer in the save file. However the new layer keras_layer expects 262 weights, but the saved weights have 260 elements.`\r\n\r\nMy command is:\r\n`python3 make_nsfw_model.py --image_dir /nsfw/training --image_size 224 --saved_model_dir /Users/bill/lab/nsfw/mobilenet_v2_140_224 --labels_output_file /nsfw/mobilenet_v2_140_224/class_labels.txt --tfhub_module https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/classification/4 --tflite_output_file /nsfw/saved_model.tflite --train_epochs 3 --batch_size 32 --do_fine_tuning --learning_rate 0.001 --dropout_rate 0.0 --momentum 0.9`","closed_by":null,"reactions":{"url":"https://api.github.com/repos/GantMan/nsfw_model/issues/77/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/GantMan/nsfw_model/issues/77/timeline","performed_via_github_app":null,"state_reason":null}