{"url":"https://api.github.com/repos/doccano/doccano/issues/1775","repository_url":"https://api.github.com/repos/doccano/doccano","labels_url":"https://api.github.com/repos/doccano/doccano/issues/1775/labels{/name}","comments_url":"https://api.github.com/repos/doccano/doccano/issues/1775/comments","events_url":"https://api.github.com/repos/doccano/doccano/issues/1775/events","html_url":"https://github.com/doccano/doccano/issues/1775","id":1196954036,"node_id":"I_kwDOB-j9wM5HWBG0","number":1775,"title":"No migrations to apply error.   Installation failed. ","user":{"login":"chenxiaozeng","id":11793384,"node_id":"MDQ6VXNlcjExNzkzMzg0","avatar_url":"https://avatars.githubusercontent.com/u/11793384?v=4","gravatar_id":"","url":"https://api.github.com/users/chenxiaozeng","html_url":"https://github.com/chenxiaozeng","followers_url":"https://api.github.com/users/chenxiaozeng/followers","following_url":"https://api.github.com/users/chenxiaozeng/following{/other_user}","gists_url":"https://api.github.com/users/chenxiaozeng/gists{/gist_id}","starred_url":"https://api.github.com/users/chenxiaozeng/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/chenxiaozeng/subscriptions","organizations_url":"https://api.github.com/users/chenxiaozeng/orgs","repos_url":"https://api.github.com/users/chenxiaozeng/repos","events_url":"https://api.github.com/users/chenxiaozeng/events{/privacy}","received_events_url":"https://api.github.com/users/chenxiaozeng/received_events","type":"User","site_admin":false},"labels":[{"id":927327719,"node_id":"MDU6TGFiZWw5MjczMjc3MTk=","url":"https://api.github.com/repos/doccano/doccano/labels/bug","name":"bug","color":"d73a4a","default":true,"description":"Something isn't working"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-04-08T07:36:10Z","updated_at":"2022-09-15T00:43:49Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"<!-- Before submitting an issue, make sure to check the docs and closed issues and FAQ to see if any of the solutions work for you. https://github.com/doccano/doccano/wiki/Frequently-Asked-Questions -->\r\n\r\nHow to reproduce the problem\r\n---------\r\n<!-- Include the details of how the problem occurred. Which option did you choose to install doccano? Did you come across an error? What else did you try? -->\r\nHI, I installed  doccano by `pip install doccano`. The output log of `doccano init` seems abnormal.\r\n![MacBook-Pro](https://user-images.githubusercontent.com/11793384/162387243-d9a8591b-9271-45b5-87e9-e67b3f34538e.png)\r\n\r\n\r\nThe front-end service can be successfully started. However, I couldn't create an annotation task. I got the err message below when I try to create an annotation task.\r\n<img width=\"563\" alt=\"Ftle •opthonebrewi1bpython3  9site-packagesdjangodbmodelsbase py•, 1in\" src=\"https://user-images.githubusercontent.com/11793384/162387028-75dbf4a4-0b26-40a9-9e53-7d61110467e7.png\">\r\n\r\n\r\n\r\nYour Environment\r\n---------\r\n<!-- Include details of your environment.-->\r\n*   Operating System:  macOS Monterey 12.1 Apple M1\r\n*   Python Version Used: 3.8/3.9\r\n*   When you install doccano: 2022/4/8\r\n*   How did you install doccano (Heroku button etc):  \r\n```bash\r\npip install doccano\r\n# Initialize database.\r\ndoccano init\r\n# Create a super user.\r\ndoccano createuser --username admin --password pass\r\n# Start a web server.\r\ndoccano webserver --port 8000\r\ndoccano task\r\n```\r\n","closed_by":null,"reactions":{"url":"https://api.github.com/repos/doccano/doccano/issues/1775/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/doccano/doccano/issues/1775/timeline","performed_via_github_app":null,"state_reason":null}