{"url":"https://api.github.com/repos/dmlc/gluon-nlp/issues/1303","repository_url":"https://api.github.com/repos/dmlc/gluon-nlp","labels_url":"https://api.github.com/repos/dmlc/gluon-nlp/issues/1303/labels{/name}","comments_url":"https://api.github.com/repos/dmlc/gluon-nlp/issues/1303/comments","events_url":"https://api.github.com/repos/dmlc/gluon-nlp/issues/1303/events","html_url":"https://github.com/dmlc/gluon-nlp/issues/1303","id":681444364,"node_id":"MDU6SXNzdWU2ODE0NDQzNjQ=","number":1303,"title":"FP16 and FP32 gives different results since GluonNLP 0.7","user":{"login":"davisliang","id":12505988,"node_id":"MDQ6VXNlcjEyNTA1OTg4","avatar_url":"https://avatars.githubusercontent.com/u/12505988?v=4","gravatar_id":"","url":"https://api.github.com/users/davisliang","html_url":"https://github.com/davisliang","followers_url":"https://api.github.com/users/davisliang/followers","following_url":"https://api.github.com/users/davisliang/following{/other_user}","gists_url":"https://api.github.com/users/davisliang/gists{/gist_id}","starred_url":"https://api.github.com/users/davisliang/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davisliang/subscriptions","organizations_url":"https://api.github.com/users/davisliang/orgs","repos_url":"https://api.github.com/users/davisliang/repos","events_url":"https://api.github.com/users/davisliang/events{/privacy}","received_events_url":"https://api.github.com/users/davisliang/received_events","type":"User","site_admin":false},"labels":[{"id":890393501,"node_id":"MDU6TGFiZWw4OTAzOTM1MDE=","url":"https://api.github.com/repos/dmlc/gluon-nlp/labels/bug","name":"bug","color":"d73a4a","default":true,"description":"Something isn't working"}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2020-08-19T00:14:53Z","updated_at":"2020-08-19T00:30:55Z","closed_at":"2020-08-19T00:30:55Z","author_association":"NONE","active_lock_reason":null,"body":"## Description\r\nDoing a forward pass with BERT-base (using the same parameters) on fp16 gives very different results from fp32. This is the case for GluonNLP beyond 0.6.0.\r\n\r\n### Error Message\r\nfrom float32:\r\n```\r\n[[[-0.14241205  0.13353725 -0.12907065 ... -0.35967964 -0.05622258\r\n    0.36050138]\r\n  [-0.350648    0.10419771  0.6244457  ... -0.17610289  0.48340237\r\n    0.06443504]\r\n  [-0.24513094 -0.15731683  0.69451946 ... -0.5654467  -0.0894002\r\n   -0.18564378]\r\n  [-0.82478666 -0.9119223  -0.65607107 ...  0.50742483 -0.19388783\r\n   -0.16587636]\r\n  [ 0.8766523   0.03524842 -0.12331446 ...  0.2720161  -0.6369005\r\n   -0.1585012 ]]]\r\n<NDArray 1x5x768 @gpu(0)>\r\n```\r\n\r\nfrom float16:\r\n```\r\n[[[-0.4473   0.03326 -0.06555 ... -0.4893  -0.1052   0.5503 ]\r\n  [-0.9287  -0.04443  0.9863  ... -0.7188  -0.1516   0.0721 ]\r\n  [-0.6553  -0.2798   0.6636  ... -0.526   -0.5      0.03748]\r\n  [-0.726   -0.81    -0.05014 ...  0.2372  -0.447    0.04047]\r\n  [-1.035   -0.578    0.5273  ... -0.4065  -0.3872   0.5005 ]]]\r\n<NDArray 1x5x768 @gpu(0)>\r\n```\r\n\r\n## To Reproduce\r\n(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)\r\n\r\n### Steps to reproduce\r\n(Paste the commands you ran that produced the error.)\r\n```python\r\n#float32\r\nimport gluonnlp as nlp; import mxnet as mx;\r\nmodel, vocab = nlp.model.get_model('bert_12_768_12', dataset_name='book_corpus_wiki_en_uncased', use_classifier=False, use_decoder=False, ctx=mx.gpu(0));\r\ntokenizer = nlp.data.BERTTokenizer(vocab, lower=True);\r\ntransform = nlp.data.BERTSentenceTransform(tokenizer, max_seq_length=512, pair=False, pad=False);\r\nsample = transform(['Hello world!']);\r\n\r\nmodel.cast('float32')\r\n\r\nwords, valid_len, segments = mx.nd.array([sample[0]]).as_in_context(mx.gpu(0)), \\\r\n                                            mx.nd.array([sample[1]]).as_in_context(mx.gpu(0)).astype('float32'), \\\r\n                                            mx.nd.array([sample[2]]).as_in_context(mx.gpu(0)).astype('float32')\r\nseq_encoding, cls_encoding = model(words, segments, valid_len);\r\n```\r\n\r\n```python\r\n# float16\r\nimport gluonnlp as nlp; import mxnet as mx;\r\nmodel, vocab = nlp.model.get_model('bert_12_768_12', dataset_name='book_corpus_wiki_en_uncased', use_classifier=False, use_decoder=False, ctx=mx.gpu(0));\r\ntokenizer = nlp.data.BERTTokenizer(vocab, lower=True);\r\ntransform = nlp.data.BERTSentenceTransform(tokenizer, max_seq_length=512, pair=False, pad=False);\r\nsample = transform(['Hello world!']);\r\n\r\nmodel.cast('float16')\r\n\r\nwords, valid_len, segments = mx.nd.array([sample[0]]).as_in_context(mx.gpu(0)), \\\r\n                                            mx.nd.array([sample[1]]).as_in_context(mx.gpu(0)).astype('float16'), \\\r\n                                            mx.nd.array([sample[2]]).as_in_context(mx.gpu(0)).astype('float16')\r\nseq_encoding, cls_encoding = model(words, segments, valid_len);\r\n```\r\n\r\n## What have you tried to solve it?\r\n1. Tried it on various gluonnlp versions. 0.6.0 does not have this bug. 0.7.0+ does.\r\n2.\r\n\r\n## Environment\r\nJust your average EC2 machine with `pip install mxnet-cu102`\r\n\r\nWe recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:\r\n```\r\ncurl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python\r\n\r\n# paste outputs here\r\n```\r\n","closed_by":{"login":"davisliang","id":12505988,"node_id":"MDQ6VXNlcjEyNTA1OTg4","avatar_url":"https://avatars.githubusercontent.com/u/12505988?v=4","gravatar_id":"","url":"https://api.github.com/users/davisliang","html_url":"https://github.com/davisliang","followers_url":"https://api.github.com/users/davisliang/followers","following_url":"https://api.github.com/users/davisliang/following{/other_user}","gists_url":"https://api.github.com/users/davisliang/gists{/gist_id}","starred_url":"https://api.github.com/users/davisliang/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davisliang/subscriptions","organizations_url":"https://api.github.com/users/davisliang/orgs","repos_url":"https://api.github.com/users/davisliang/repos","events_url":"https://api.github.com/users/davisliang/events{/privacy}","received_events_url":"https://api.github.com/users/davisliang/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/dmlc/gluon-nlp/issues/1303/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/dmlc/gluon-nlp/issues/1303/timeline","performed_via_github_app":null,"state_reason":"completed"}